// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[Table("Course")]
public partial class Course
{
    [Key]
    public int Course_ID { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Crs_Name { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<Exam_Structure> Exam_Structures { get; set; } = new List<Exam_Structure>();

    [InverseProperty("Course")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Course")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    [ForeignKey("Course_ID")]
    [InverseProperty("Courses")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [ForeignKey("Course_ID")]
    [InverseProperty("Courses")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}