// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int Exam_ID { get; set; }

    public int Student_ID { get; set; }

    public int? Grade { get; set; }

    public int Structure_ID { get; set; }

    [ForeignKey("Structure_ID")]
    [InverseProperty("Exams")]
    public virtual Exam_Structure Structure { get; set; }

    [ForeignKey("Student_ID")]
    [InverseProperty("Exams")]
    public virtual Student Student { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    [ForeignKey("Exam_ID")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}