// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[Table("Question")]
public partial class Question
{
    [Key]
    public int Question_ID { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string Type { get; set; }

    [Required]
    [Column("Question")]
    [StringLength(200)]
    [Unicode(false)]
    public string Question1 { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Model_Answer { get; set; }

    public int Course_ID { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [ForeignKey("Course_ID")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    [ForeignKey("Question_ID")]
    [InverseProperty("Questions")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}