// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class Select_Exam_QuestionResult
    {
        public int Question_ID { get; set; }
        public string Type { get; set; }
        public string Question { get; set; }
        public string Model_Answer { get; set; }
        public int Course_ID { get; set; }
    }
}
