// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[PrimaryKey("Question_ID", "Choices")]
public partial class Choice
{
    [Key]
    public int Question_ID { get; set; }

    [Key]
    [StringLength(200)]
    [Unicode(false)]
    public string Choices { get; set; }

    [ForeignKey("Question_ID")]
    [InverseProperty("Choices")]
    public virtual Question Question { get; set; }
}