// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[Table("Instructor")]
public partial class Instructor
{
    [Key]
    public int Instructor_ID { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string First_Name { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Second_Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    public int? Dept_ID { get; set; }

    [ForeignKey("Dept_ID")]
    [InverseProperty("Instructors")]
    public virtual Department Dept { get; set; }

    [ForeignKey("Instructor_ID")]
    [InverseProperty("Instructors")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}