// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[Table("Student")]
public partial class Student
{
    [Key]
    public int Student_ID { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string First_Name { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Second_Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    public int? Dept_ID { get; set; }

    [ForeignKey("Dept_ID")]
    [InverseProperty("Students")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Student")]
    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    [ForeignKey("Student_ID")]
    [InverseProperty("Students")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}