// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Entities;

[PrimaryKey("Course_ID", "Topic_Name")]
[Table("Topic")]
public partial class Topic
{
    [Key]
    public int Course_ID { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Topic_Name { get; set; }

    [ForeignKey("Course_ID")]
    [InverseProperty("Topics")]
    public virtual Course Course { get; set; }
}