// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Context
{
    public partial class ExaminationSystemContext
    {
        private IExaminationSystemContextProcedures _procedures;

        public virtual IExaminationSystemContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ExaminationSystemContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IExaminationSystemContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Select_ChoicesResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<Select_Exam_QuestionResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStudentExamsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class ExaminationSystemContextProcedures : IExaminationSystemContextProcedures
    {
        private readonly ExaminationSystemContext _context;

        public ExaminationSystemContextProcedures(ExaminationSystemContext context)
        {
            _context = context;
        }

        public virtual async Task<List<Select_ChoicesResult>> Select_ChoicesAsync(int? qid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "qid",
                    Value = qid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_ChoicesResult>("EXEC @returnValue = [dbo].[Select_Choices] @qid", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Select_Exam_QuestionResult>> Select_Exam_QuestionAsync(int? Exam_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Exam_id",
                    Value = Exam_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_Exam_QuestionResult>("EXEC @returnValue = [dbo].[Select_Exam_Question] @Exam_id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStudentExamsResult>> SelectStudentExamsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStudentExamsResult>("EXEC @returnValue = [dbo].[SelectStudentExams]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
