// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Context
{
    public partial interface IExaminationSystemContextProcedures
    {
        Task<List<Select_ChoicesResult>> Select_ChoicesAsync(int? qid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_Exam_QuestionResult>> Select_Exam_QuestionAsync(int? Exam_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectStudentExamsResult>> SelectStudentExamsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
